spring.application.name=BookStorage
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate

jwt.secret=ThisIsSecretKeyForJwtAndMyProject
jwt.expiration=500000
